apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app-container
          image: sachinpachpute/gitops-demo-app:8
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32000
  selector:
    app: spring-app