apiVersion: apps/v1 # Kubernetes API version
kind: Deployment  # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: sachinpachpute/spring-boot-k8s:V1
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster
---

kind: Service  # Kubernetes API version
apiVersion: v1 # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 80   # The port that the service is running on in the cluster
      targetPort: 80   # The port exposed by the service
      nodePort: 31000
  type: NodePort     # type of the service.